package main.java.gui;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import main.java.gui.RekinadoMain.UIListener;
import java.awt.Polygon;
import java.awt.image.BufferedImage;
import main.java.rankine.TornadoGUI;
import main.java.trees.Forest;
import main.java.trees.TreeGUI;

/**
 * Klasa Głównego okna GUI
 * 
 * @author Jacek Pietras
 */
public class GUInterface extends javax.swing.JFrame{

	private static boolean started = false;
	private GUIInfo infoBox = null;
	private GUIParam param = null;
	
	public GUInterface() {
		initComponents();
		if (!started) {
			this.add(BG);
			started = true;
			start();
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnParam = new javax.swing.JButton();
        btnSim = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jSlider1 = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        BG = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "kontrola"));
        jPanel3.setName("nowa krzyzowka"); // NOI18N

        btnParam.setText("Parametry");
        btnParam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnParamMouseClicked(evt);
            }
        });
        btnParam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParamActionPerformed(evt);
            }
        });

        btnSim.setText("Start");
        btnSim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimMouseClicked(evt);
            }
        });
        btnSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetMouseClicked(evt);
            }
        });
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jSlider1.setMaximum(50);
        jSlider1.setMinimum(5);
        jSlider1.setValue(40);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });

        jLabel1.setText("Powiększenie");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btnParam, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSim, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnParam)
                        .addComponent(btnSim)
                        .addComponent(btnReset)
                        .addComponent(jLabel1))))
        );

        BG.setBackground(new java.awt.Color(255, 255, 255));
        BG.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BG.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                BGComponentResized(evt);
            }
        });

        javax.swing.GroupLayout BGLayout = new javax.swing.GroupLayout(BG);
        BG.setLayout(BGLayout);
        BGLayout.setHorizontalGroup(
            BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 772, Short.MAX_VALUE)
        );
        BGLayout.setVerticalGroup(
            BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
       //listener.actualizeUI(this);
	   //listener.print();
    }//GEN-LAST:event_formComponentResized

    private void BGComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_BGComponentResized
		listener.actualizeUI(this);
		listener.print();
    }//GEN-LAST:event_BGComponentResized

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseClicked
        listener.actualizeUI(this);
        listener.reset();
    }//GEN-LAST:event_btnResetMouseClicked

    private void btnSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimActionPerformed

    private void btnSimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimMouseClicked
        btnSimAction();

    }//GEN-LAST:event_btnSimMouseClicked

    private void btnParamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParamActionPerformed

    }//GEN-LAST:event_btnParamActionPerformed

    private void btnParamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnParamMouseClicked
        //listener.actualizeUI(this);
        showParam();
    }//GEN-LAST:event_btnParamMouseClicked

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        //System.out.printf(((double)jSlider1.getValue())/20+"\n");
		printscale = ((double)jSlider1.getValue())/20;
		
		listener.actualizeUI(this);
		listener.print();
    }//GEN-LAST:event_jSlider1StateChanged

	public void btnSimAction(){
		listener.actualizeUI(this);
		listener.run = !listener.run;
		
		if(listener.run){
			listener.start();
			btnSim.setText("Stop");
		}
		else{
			listener.stop();
			btnSim.setText("Start");
		}
	}
	public static void start() {
		/* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(GUInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(GUInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(GUInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(GUInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
        //</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				new GUInterface().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JButton btnParam;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSlider jSlider1;
    // End of variables declaration//GEN-END:variables
       
	private static UIListener listener;

	/**
	 * Dodaje nasłuchiwacza eventów do gui
	 * 
	 * @param l nowy listener
	 */
	public void addListener(UIListener l) {
		listener = l;
		listener.actualizeUI(this);
	}

	/**
	 * Wyświetla okienko błędu
	 * @param text tekst do wyświetlenia
	 */
	public void dialog(String text){
		if(infoBox == null) infoBox = new GUIInfo(this, false);
		infoBox.setVisible(false);
		infoBox.setLocationRelativeTo(this);
		infoBox.setText(text);
		//infoBox.setTitle(text);
		infoBox.setVisible(true);
	}
	
	
	
	private void showParam(){
		if(param == null) param = new GUIParam(this, false);
		param.setVisible(false);
		param.setLocationRelativeTo(this);
		param.setVisible(true);
		param.fill(listener);
		//System.out.printf("Okno parametrów\n");
	}
	
	/**
	 * Zoom w grafice
	 */
	private static double printscale = 2;
	
	/**
	 * Wymiary Obszaru Wizualizacji
	 */
	private static int bgW, bgH ;	
	
	private static BufferedImage canvas = null;	
	private static double sin45 = Math.sin(Math.PI/4);
	
	/**
	 * Rzutuje tablice [x][y][z] na izometryczny rzut 2d
	 * 
	 * @param tab tablica [x][y][z]
	 * @return współrzędna x
	 */
	public static int toIzoX(double tab[]){
		return (int) Math.round((tab[0]+sin45*tab[1])*printscale);
	}

	/**
	 * Rzutuje tablice [x][y][z] na izometryczny rzut 2d
	 * 
	 * @param tab tablica [x][y][z]
	 * @return współrzędna y
	 */
	public static int toIzoY(double tab[]){
		//.7 to magiczna stała piękności
		return (int)-Math.round((tab[2]+sin45*tab[1])*printscale*.7); 
	}

	/**
	 * Normalizuje punkty Polygon do środka obrazka
	 * 
	 * @param p Polygon do znormalizowania
	 * @return znormalizowany Polygon
	 */
	public static Polygon normToCenter(Polygon p){ // To center of Word
		for(int i=0; i<p.npoints;i++){
			p.xpoints[i]+=(bgW/2 );
			p.ypoints[i]+=(bgH/2);
		}
		return p;
	}
	


	/**
	 * Rysuje białe tło w obszarze wizualizacji
	 * 
	 * @param g Graphics
	 */
	private void bgDraw(Graphics g){
		g.setColor(Color.white);
		g.fillRect(1, 1, bgW - 2, bgH - 2);
	}
	
	/**
	 * Rysuje rzut poziomy lasu
	 * @param g Graphics
	 * @param tree tablica drzew
	 * @param ntree liczba drzew
	 */
	private void miniatureDraw(Graphics g, TreeGUI tree[], int ntree){
		int x = 5;
		int y = 5;
		int h = 200;
		int w = 200;
		int terrainWidth = TerrainGUI.height;
		int terrainHeight = TerrainGUI.width;
		
		int treeX;
		int treeY;
		
		double Xr = (w/(double)terrainWidth );
		double Yr = (h/(double)terrainHeight);
		int treeXs;
		int treeYs;
		
		double angle;
		
		g.setColor(Color.black);
		g.fillRect(x-2, y-2, w+4, h+4);
		g.setColor(Color.white);
		g.fillRect(x-1, y-1, w+2, h+2);
		
		for(int i=0;i<ntree;i++){
			treeX = (int) ( x+( tree[i].x)*Xr+w/2);
			treeY = (int) ( y+(-tree[i].y)*Yr+h/2);
			treeXs = (int) ((Xr)*(tree[i].currentwindPower)*5 +1);
			treeYs = (int) ((Yr)*(tree[i].currentwindPower)*5 +1);
			
			angle = tree[i].windRotation*Math.PI;
			g.setColor(tree[i].getCrownColor());			
			drawBoldLine(g,
					treeX,treeY,
					treeX+(int)(treeXs*Math.sin(angle)),
					treeY+(int)(treeYs*Math.cos(angle)));
		}
	}
	private void drawBoldLine(Graphics g, int x1, int y1, int x2, int y2){
		g.drawLine(x1, y1, x2, y2);
		g.drawLine(x1+1, y1, x2+1, y2);
		g.drawLine(x1, y1+1, x2, y2+1);
		g.drawLine(x1+1, y1+1, x2+1, y2+1);
	}
		
	/**
	 * Wyświetla ramke wizualizacji
	 */
	public void printFrame() {
		TreeGUI tree[] = Forest.getList();
		int ntree = Forest.getLength();
		bgW  = BG.getWidth();
		bgH = BG.getHeight();
		Boolean tornadoWasDrawn = false;
		double tornadoDist = TornadoGUI.x-TornadoGUI.y+TornadoGUI.radius(0);
		
		canvas = new BufferedImage(bgW,bgH,BufferedImage.TYPE_INT_ARGB);
		Graphics g = canvas.createGraphics();
				
		bgDraw(g);
		TerrainGUI.draw(g);
		
		for(int i=0; i<ntree;i++){
			tree[i].drawShadow(g);
		}
		for(int i=0; i<ntree;i++){
			if(!tornadoWasDrawn && tornadoDist<tree[i].x-tree[i].y){
				tornadoWasDrawn = true;
				TornadoGUI.drawShadow(canvas,bgW/2,bgH/2);
				TornadoGUI.draw(canvas,bgW/2,bgH/2);
				//TornadoGUI.moveParticles();
			}
			/*for(int j=0; j<ntree;j++){ //Kolicje wywalic z grafiki
				if(tree[i].collisionTest(tree[j])){
					//tree[i].crack();
					//tree[j].crack();
					System.out.println("Kolizja ["+i+"] i ["+j+"]");
				}
			}*/
			tree[i].draw(g);
		}
						
		miniatureDraw(g, tree, ntree);
        ((Graphics2D) BG.getGraphics()).drawImage(canvas, null, null);
	}	
	
	
}
